version: "3.8"
services:
  redis:
    image: redis:6
    ports:
      - 6379:6379
  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: local
      POSTGRES_USER: bubble
    ports:
      - 5432:5432
    volumes:
      - ./_local_db/db:/var/lib/postgresql/data
